### ISSUE TITLE
bug: Unable to view any Course Video

### ISSUE THREAD

**Issue by Vortex1806** [code100x/cms#1602] opened 2024-12-02 07:11 UTC
**Describe the bug**
On all pages of course the video are not visible for 0-100 course 

**To Reproduce**
1. open 0-100 course
2. open any week
3. open any video

**Expected behavior**
Show the Course video

**Screenshots or GIFs**
![Capture](https://github.com/user-attachments/assets/7484d3cb-1fc1-43e2-b120-b1e0249205a0)

**Info (please complete the following information):**
 - Browser chrome

**Additional context**

**Comment by anniop** [comment] 2024-12-02 07:15
i think the problem is on your side not the server side because i can see all the videos perfectly please change the browser and check again

**Comment by ShAhilK2** [comment] 2024-12-02 08:42
Oops! Something went wrong
An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.

**Comment by barathraj048** [comment] 2024-12-02 09:32
i cant able to play

**Comment by Vortex1806** [comment] 2024-12-02 09:48
> i think the problem is on your side not the server side because i can see all the videos perfectly please change the browser and check again

I have tried doing that too using different browser and different machine still have the same error

**Comment by Smnthjm08** [comment] 2024-12-04 05:20
try in incognito mode and if the issue persist, contact rookie

**Comment by Vortex1806** [comment] 2024-12-04 05:54
It is working again since yesterday if possible please close the issue

**Comment by pushkar707** [comment] 2024-12-05 06:22
@Vortex1806 You can close the issue yourself

**Comment by Vortex1806** [comment] 2024-12-06 04:22
Issue from backend 
Working now

**Closed** 2024-12-06 04:22 UTC
Labels: bug
