### ISSUE TITLE
bug: The page direction in the notes on cms is redirecting to wrong URL

### ISSUE THREAD

**Issue by Ayush-Baliyan-19** [code100x/cms#1050] opened 2024-08-27 07:52 UTC
When Clicking on button to redirect in notes of section, the redirect is at wrong URL for e.g. I was on week 17.1 Notes, was going through notes, when I clicked on week 17 in notes,I was redirected to a wrong URL
<img width="1512" alt="Screenshot 2024-08-27 at 1 16 20 PM" src="https://github.com/user-attachments/assets/1d2acafa-57ca-42bd-bf04-444a926cde3b">

Expected behaviour
It should redirect to the correct URL such as https://app.100xdevs.com/courses/3/245

**Comment by malisettisamrat** [comment] 2024-08-27 08:12
Hi @Ayush-Baliyan-19, Can I work on this issue?

**Comment by MeerUzairWasHere** [comment] 2024-09-04 17:21
We can pass `disableHeader={true}`.

@hkirat , @devsargam  , I've investigated the issue, and it's not a bug on our end. We're using `import { NotionRenderer as NotionRendererLib } from 'react-notion-x';` and passing records to this component that come from the Notion API. I don't think we can customize this, but we can disable the header from that component since we already have our own breadcrumb just above it.

Please assign this to me, as I've already figured out the solution. @hkirat  @devsargam 

![image](https://github.com/user-attachments/assets/d7973633-a66d-4ee5-ae6f-808588f7effc)

**Comment by MeerUzairWasHere** [comment] 2024-09-05 09:33
Sorry, something was wrong with the firist PR, I created new one.

**Closed** 2024-09-05 11:32 UTC
Labels: bug
