### ISSUE TITLE
bug: video titles not visible for chrome (on linux)... 0 -100 cohort

### ISSUE THREAD

**Issue by ABDREHMAN6224** [code100x/cms#1652] opened 2024-12-12 18:09 UTC
**Describe the bug**
When in desktop view we click on show contents and side bar opens, the title is not visible

**To Reproduce**
1. click show contents on video page and expand dropdown

**Expected behavior**
title of vidoe should appear

**Screenshots or GIFs**
![image](https://github.com/user-attachments/assets/699deb55-3155-4329-827d-27d53daef12d)

**Info (please complete the following information):**
 - Browser  Chrome
 - Version 131.0.6778.85 (Official Build) (64-bit)

**Comment by ganeshkondaka** [comment] 2024-12-13 05:56
Many people have already raised this issue...

**Comment by iamlikeaproforyou** [comment] 2024-12-13 06:58
The issue is fixed in main branch
need to deploy the fix to the production branch

**Closed** 2024-12-13 16:02 UTC
Labels: bug
