### ISSUE TITLE
bug: Discord server link unavailable 

### ISSUE THREAD

**Issue by sitanshu05** [code100x/cms#1437] opened 2024-10-05 19:48 UTC
**Describe the bug**
Discord Link not available on app.100x.devs for the purchased cohort 

**To Reproduce**
1. Leave discord
2. open app.100x.devs
3. view courses

**Expected behavior**
A discord link for the purchased course, but instead there is only claim certificate and the discord link of other courses 

**Screenshots or GIFs**
<img width="1263" alt="Screenshot 2024-10-06 at 1 17 35 AM" src="https://github.com/user-attachments/assets/09c4c74a-597a-4fb1-a45c-2b50aa093b99">

**Additional context**
Got this issue when I left the Discord server as I was unable to text in a few channels and my sub group and discovered it when I tried to rejoin the server. 

<img width="844" alt="Screenshot 2024-10-06 at 1 39 04 AM" src="https://github.com/user-attachments/assets/2d92910c-1d00-4598-879d-a29af6c22450">

This check should not be based on the certificate being issued instead it should be a check if the email/user is present in the discord or not

I think the check needs to be changed to a db call to verify if the userId is present in the DiscordConnect table

**Comment by Aryam2121** [comment] 2024-10-08 11:56
hey i would like to work on this bug

**Comment by devsargam** [comment] 2024-10-08 21:15
🤔

**Comment by devsargam** [comment] 2024-10-08 21:15
Is this fixed @Aryam2121?

**Comment by BadriVishalPadhy** [comment] 2024-10-10 15:10
🤔

**Comment by Aryam2121** [comment] 2024-10-12 12:26
yeah it's fixed

**Comment by avparadox** [comment] 2024-10-21 17:12
Hey @sitanshu05,

This is not a bug. cms is designed in a way that 1 user should be able to join the discord server only once. If you have exited the server then please contact Rookie or you can mail at 100xdevs@gmail.com asking for a rejoin. They will help you out there. 

Please close this issue. Thank You.

**Comment by avparadox** [comment] 2024-10-25 18:21
Hey @devsargam please close this one. Not an issue here.

**Closed** 2024-10-25 22:34 UTC
Labels: bug
