### ISSUE TITLE
bug: Screen area is filled too much by navbar on the top and appbar on the bottom. Video size is not fit for the screen size

### ISSUE THREAD

**Issue by ankit0tech** [code100x/cms#1551] opened 2024-11-07 06:47 UTC
**Describe the bug**
Screen area is filled too much by navbar with show content button on the top and appbar on the bottom. It makes difficult to navigate through the course contents. Video size is not fit for the screen size.

**To Reproduce**
1. Sign in and open any course content
2. Most of the screen is taken up by the navbar and appbar.
3. Play any video without entering into fullscreen. Video content is not much visible.

**Expected behavior**
1. navbar can have smaller height.
2. appbar can be completely removed from the bottom because all the options are already available in the profile button in the navbar.
3. video size can be smaller.

**Screenshots or GIFs**
![image](https://github.com/user-attachments/assets/d0d1bd85-2ac0-484a-bb81-d46ed70c9c57)
![image](https://github.com/user-attachments/assets/d082b75d-ee3f-46b2-8ab3-59dff99db20d)

**Comment by ankit0tech** [comment] 2024-11-08 07:21
Hi @hkirat , @siinghd can you please check this?

**Comment by pankajsingh016** [comment] 2024-11-19 11:42
The problem is there as the video resolution of the sample video dosen't matches with the  uploaded recording.

**Comment by ankit0tech** [comment] 2024-11-20 01:46
I have tried different videos with different resolutions locally, they are working fine.

**Comment by saurabhraghuvanshii** [comment] 2024-11-21 12:27
@ankit0tech because it fixes but not on production

**Comment by saurabhraghuvanshii** [comment] 2024-11-21 14:05
@ankit0tech are you experience it locally, if then update your repo locally from upstream aor rebase it

**Comment by devsargam** [comment] 2024-12-06 19:38
This has been already addressed closing

**Closed by devsargam** 2024-12-06 19:38 UTC
Labels: bug

**Comment by ankit0tech** [comment] 2024-12-14 11:57
Hi @devsargam, I don't see the issue being fixed on main website app.100xdevs.com, If there is any PR that fixes the issue can you please share the link.
