### ISSUE TITLE
bug: Incorrect Greeting

### ISSUE THREAD

**Issue by aadityesh** [code100x/cms#1182] opened 2024-09-11 01:57 UTC
**Describe the bug**
The application is currently displaying the greeting "Good evening" at 7 AM, which is incorrect. The expected behavior is to display "Good morning" during the morning hours. I have added the complete desktop screenshot along with the taskbar displaying the current time when this bug was visible.

**Screenshots or GIFs**
![image](https://github.com/user-attachments/assets/3b2423e3-4a40-4161-8df3-ddfa1925052d)

**Comment by ItsFlash10** [comment] 2024-09-11 03:00
This is probably because of the server's timezone where the code is deployed as this screen is SSR.

**Comment by Kaif9999** [comment] 2024-09-12 00:37
I think we can display the greeting instead of using the server's timezone to display the greeting we should greet the user with a message based on the client location timezone

**Comment by viveksuyal37** [comment] 2024-09-13 10:29
Happy to fix this. The problem is that the client could be on a different time zone from server, which is causing the issue. I'll make it client side.  Could you please assign it to me? Thanks!

**Closed** 2024-09-25 23:04 UTC
Labels: bug
